name: Develop-Pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      TEST_DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB: ${{secrets.DB}}
      PAGE: ${{secrets.PAGE}}
      PAGE_SIZE: ${{secrets.PAGE_SIZE}}
      ORDERING: ${{secrets.ORDERING}}

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: ${{secrets.DB}}
          MYSQL_PASSWORD: ${{secrets.DB_PASSWORD}}
          MYSQL_USER: ${{secrets.DB_USER}}
          MYSQL_ROOT_PASSWORD: ${{secrets.DB_PASSWORD}}
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Cloning the Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.1"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Grant MySql Permissions
        run: mysql -h 127.0.0.1 --port 3307 -u root -p${{secrets.DB_PASSWORD}} -e "GRANT ALL PRIVILEGES ON test.* TO 'app_user'@'%';FLUSH PRIVILEGES;"
        # run: mysql -u root -p

      - name: Run tests
        run: poetry run task test
